ACE_Project/ACE_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from ACE_app import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index,name='index'),
    path('',include('ACE_app.urls')),
    path('ACE_app/',include('ACE_app.urls')),
    path('formpage/',views.form_name_view, name='form_name'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),

]

ACE_Project/ACE_app/urls.py
from django.urls import path
from ACE_app import views

# For TEMPLATE TAGGING
app_name = 'ACE_app'

urlpatterns = [

    path('',views.index,name='index'),
    path('help/',views.help,name='help'),
    path('users/', views.users, name='users'),
    path('relative/', views.relative, name='relative'),
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),

]

ACE_Project/ACE_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here. store data models, the entities and relationships
class UserProfileInfo(models.Model):
    # Extending the User class
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # username is one of the default attributes of the User
        return self.user.username


class Topic(models.Model):
    top_name = models.CharField(max_length=264)

    #string representation of model for easy printing out
    def __str__(self):
        return self.top_name
    
class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)
    
class User(models.Model):
    first = models.CharField(max_length=128)
    last = models.CharField(max_length=128)
    email = models.EmailField(max_length=264, unique=True)

ACE_Project/ACE_app/forms.py
from django import forms
from django.contrib.auth.models import User
from ACE_app.models import UserProfileInfo

class NewUserForm(forms.ModelForm):
    class Meta():
        model = User
        fields ="__all__"

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

ACE_Project/ACE_app/views.py
from django.shortcuts import render
from ACE_app.models import Topic, User, Webpage, AccessRecord
from . import forms  
from ACE_app.forms import NewUserForm, UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse 
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here. Store functions to handle requests and return responses

def index(request):
    #context_dict = {'text':'hello world','number':100}
    return render(request,'ACE_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")


def register(request):

    registered = False

    if request.method == "POST":
        #matches variable sent to template tagging
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password) #hashing the password
            user.save()

            profile = profile_form.save(commit=False) # avoid potential collisions the first time through
            profile.user = user # sets up the one-one relationship

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'ACE_app/registration.html',{'user_form':user_form, 'profile_form':profile_form, 'registered':registered})


def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username= username, password= password) #Django's built-in authenticator

        if user:
            if user.is_active:
                login(request,user) #another built in
                return HttpResponseRedirect(reverse('index')) #will send back to home page if active
            else:
                return HttpResponse("Account not Active!")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'ACE_app/login.html',{})

def other(request):
    return render(request,'ACE_app/other.html')

def relative(request):
    return render(request,'ACE_app/relative_url_templates.html')

def form_name_view(request):
    form=forms.FormName()

    if request.method == "POST":
        form=forms.FormName(request.POST)

        if form.is_valid():
            #Do something
            print("VALIDATION SUCCESS!")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: "+form.cleaned_data['text'])


    return render(request, 'ACE_app/form_page.html',{'form':form})


def help(request):
    help_dict = {'help_insert':"Help Page"}
    return render(request,'ACE_app/help.html',context=help_dict)

def users(request):
    form = NewUserForm()

    if request.method=="POST":
        form=NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("ERROR FORM not valid")
    return render(request,'ACE_app/users.html',{'form':form})

ACE_Project/templates/ACE_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
    
</head>
<body>
    <nav class="navbar navbar-default navbar-light bg-light navbar-static-top">
        <div class="container">
            <ul class="nav navbar-default">
                <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="nav-link" href="{% url 'ACE_app:register' %}">Register</a></li>

                {% if user.is_authenticated %}
                    <li><a class='nav-link' href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a class='nav-link' href="{% url 'ACE_app:user_login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        Anything outside of this will be inherited if you extend
        {% endblock %}
    </div>
</body>
</html>

ACE_Project/templates/ACE_app/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>Forms</title>
</head>
<body>
    <h1>Fill out the form:</h1>
    <div class="container">
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</body>
</html>

ACE_Project/templates/ACE_app/help.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>ACE Application Help File</title>
    </head>
    <body>

        <h1>Hello, this is is a page to get assistance you might need from help.html!</h1>
        {{ help_insert }}
    </body>
</html>

ACE_Project/templates/ACE_app/index.html
<!DOCTYPE html>

{% extends "ACE_app/base.html" %}
{% load my_extras %}
{% block body_block %}
{% load static %}
<div class = 'jumbotron'>
    <h1>Welcome to Level Five</h1>
    <img src={% static "ACE_app/images/kelp.jpg" %} alt="Uh oh, didn't show!">
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:"99" }}</h1>
    <h2> Go to /users to sign up</h2>
    <h2> Go to /formpage to fill out the form</h2>

</div>    
        
        
    {% endblock %}

ACE_Project/templates/ACE_app/login.html
{% extends 'ACE_app/base.html' %}
{% block body_block %}

<div class = 'container-fluid text-sm-center p-5 bg-light'>
    <h1 class='display-2 pt-5'> Please Login</h1>
    <p class='lead'>
        <form action="{% url 'ACE_app:user_login' %}">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="password">Password:</label>
            <input type="password" name="password">

            <input type="submit" name="" value="Login">
        </form>  
    </p>    



</div>

{% endblock %}

ACE_Project/templates/ACE_app/other.html
<!DOCTYPE html>
{% extends "ACE_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to Other!</h1>
        <h2>This is an example of template inheritance</h2>
    {% endblock %}

ACE_Project/templates/ACE_app/registration.html
{% extends "ACE_app/base.html" %}
{% load static %}

{% block body_block %}

<div class = 'jumbotron'>
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!--Below variables are part of context dictionary-->  
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <input type="submit" name="" value = "Register">
    </form>

</div>




{% endblock %}

ACE_Project/templates/ACE_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'ACE_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">Link to Admin</a>
    <a href="{% url 'index' %}">Link to Index!</a>
</body>
</html>

ACE_Project/templates/ACE_app/users.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <meta charset="utf-8">
        <title>ACE Application User List</title>
        <link rel="stylesheet" href="{% static "css/mystyle.css" %}" />
    </head>
    <body>
        <div class="container">
            <h1>Please sign up here!</h1>
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Submit">

            </form>
        </div>  
        

                
        </div>
    </body>
</html>